server:
  port: 9324
  servlet:
    context-path: /api/v1
spring:
  profiles:
    active: prod


#spring:
#  datasource:
#    url: jdbc:mysql://119.23.179.219:3306/accounting?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: "root"
#    password: "@Aliyun502624709"
#  jpa:
#    show-sql: true
#    open-in-view: true
#    hibernate:
#      ddl-auto: update
#logging:
#  level:
#    org.springframework.security: debug
#    com.github.zhangquanli.security: debug

