spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accounting?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: "root"
    password: "root"
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: debug
    com.github.zhangquanli.security: debug
