server:
  port: 9324
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accounting?useUnicode=true&charactereEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
